<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8Jp2XtT\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8Jp2XtT/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/Container8Jp2XtT.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\Container8Jp2XtT\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \Container8Jp2XtT\App_KernelTestDebugContainer([
    'container.build_hash' => '8Jp2XtT',
    'container.build_id' => 'afccd8e3',
    'container.build_time' => 1762358674,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container8Jp2XtT');
