<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQxWhbo8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQxWhbo8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQxWhbo8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQxWhbo8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQxWhbo8\App_KernelDevDebugContainer([
    'container.build_hash' => 'QxWhbo8',
    'container.build_id' => 'c3607eb3',
    'container.build_time' => 1762355856,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQxWhbo8');
