<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'nurse_create' => [[], ['_controller' => 'App\\Controller\\NurseController::create'], [], [['text', '/nurse/create']], [], [], []],
    'nurse_find_by_name' => [['name'], ['_controller' => 'App\\Controller\\NurseController::findByName'], [], [['variable', '/', '[^/]++', 'name', true], ['text', '/nurse/name']], [], [], []],
    'nurse_find_by_id' => [['id'], ['_controller' => 'App\\Controller\\NurseController::findById'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/nurse/id']], [], [], []],
    'nurse_getAll' => [[], ['_controller' => 'App\\Controller\\NurseController::getAll'], [], [['text', '/nurse/index']], [], [], []],
    'nurse_update' => [['id'], ['_controller' => 'App\\Controller\\NurseController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/nurse']], [], [], []],
    'nurse_delete' => [['id'], ['_controller' => 'App\\Controller\\NurseController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/nurse']], [], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\NurseController::login'], [], [['text', '/nurse/login']], [], [], []],
    'App\Controller\NurseController::create' => [[], ['_controller' => 'App\\Controller\\NurseController::create'], [], [['text', '/nurse/create']], [], [], []],
    'App\Controller\NurseController::findByName' => [['name'], ['_controller' => 'App\\Controller\\NurseController::findByName'], [], [['variable', '/', '[^/]++', 'name', true], ['text', '/nurse/name']], [], [], []],
    'App\Controller\NurseController::findById' => [['id'], ['_controller' => 'App\\Controller\\NurseController::findById'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/nurse/id']], [], [], []],
    'App\Controller\NurseController::getAll' => [[], ['_controller' => 'App\\Controller\\NurseController::getAll'], [], [['text', '/nurse/index']], [], [], []],
    'App\Controller\NurseController::update' => [['id'], ['_controller' => 'App\\Controller\\NurseController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/nurse']], [], [], []],
    'App\Controller\NurseController::delete' => [['id'], ['_controller' => 'App\\Controller\\NurseController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/nurse']], [], [], []],
    'App\Controller\NurseController::login' => [[], ['_controller' => 'App\\Controller\\NurseController::login'], [], [['text', '/nurse/login']], [], [], []],
];
